[tool.poetry]
name = "virtual-contributor-engine-expert"
version = "0.12.0"
description = "Alkemio Generative AI Virtul Persona"
authors = ["Alkemio BV <info@alkem.io>"]
license = "EUPL-1.2"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
langchain = "0.3.25"
langchain-core = "0.3.68"
langchain-community = "0.3.25"
load-dotenv = "0.1.0"
async-timeout = "4.0.3"
aio-pika = "9.3.1"
aiormq = "6.7.7"
azure-ai-inference = "1.0.0b4"
langchain-openai = "0.2.9"
alkemio-virtual-contributor-engine = {git = "https://git@github.com/alkem-io/virtual-contributor-engine.git", rev = "v0.0.4"}
langgraph = "^0.4.8"
chromadb = "^1.0.12"
langchain-mistralai = "^0.2.11"

[tool.poetry.group.dev.dependencies]
flake8 = "6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

